apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: stable
  pass_credentials_all: false
  password: ""
  url: https://charts.helm.sh/stable
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: incubator
  pass_credentials_all: false
  password: ""
  url: https://charts.helm.sh/incubator
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jenkinsci
  pass_credentials_all: false
  password: ""
  url: https://charts.jenkins.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: traefik
  pass_credentials_all: false
  password: ""
  url: https://helm.traefik.io/traefik
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: loki
  pass_credentials_all: false
  password: ""
  url: https://grafana.github.io/loki/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: grafana
  pass_credentials_all: false
  password: ""
  url: https://grafana.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kong
  pass_credentials_all: false
  password: ""
  url: https://charts.konghq.com
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: eks
  pass_credentials_all: false
  password: ""
  url: https://aws.github.io/eks-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kuma
  pass_credentials_all: false
  password: ""
  url: https://kumahq.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bitnami
  pass_credentials_all: false
  password: ""
  url: https://charts.bitnami.com/bitnami
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: ingress-nginx
  pass_credentials_all: false
  password: ""
  url: https://kubernetes.github.io/ingress-nginx
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: codecentric
  pass_credentials_all: false
  password: ""
  url: https://codecentric.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nvdp
  pass_credentials_all: false
  password: ""
  url: https://nvidia.github.io/k8s-device-plugin
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: gpu-helm-charts
  pass_credentials_all: false
  password: ""
  url: https://nvidia.github.io/gpu-monitoring-tools/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: aws-ebs-csi-driver
  pass_credentials_all: false
  password: ""
  url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: hashicorp
  pass_credentials_all: false
  password: ""
  url: https://helm.releases.hashicorp.com
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: appscode
  pass_credentials_all: false
  password: ""
  url: https://charts.appscode.com/stable/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: datadog
  pass_credentials_all: false
  password: ""
  url: https://helm.datadoghq.com
  username: ""
